<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="shhinduj-p51" name="org.tibco.automation.common.testcases.tsc_navbar.MainHelpPage_HelpTopics_Tests" tests="5" failures="2" timestamp="17 Apr 2019 09:43:21 GMT" time="72.230" errors="0">
  <testcase name="ta_51" time="6.438" classname="org.tibco.automation.common.testcases.tsc_navbar.MainHelpPage_HelpTopics_Tests"/>
  <testcase name="ta_51" time="3.267" classname="org.tibco.automation.common.testcases.tsc_navbar.MainHelpPage_HelpTopics_Tests"/>
  <testcase name="ta_51" time="36.584" classname="org.tibco.automation.common.testcases.tsc_navbar.MainHelpPage_HelpTopics_Tests"/>
  <testcase name="ta_52" time="12.272" classname="org.tibco.automation.common.testcases.tsc_navbar.MainHelpPage_HelpTopics_Tests">
    <failure type="java.lang.AssertionError" message="URL Manipulation Found">
      <![CDATA[java.lang.AssertionError: URL Manipulation Foundat org.testng.Assert.fail(Assert.java:96)at org.tibco.automation.common.testcases.tsc_navbar.MainHelpPage_HelpTopics_Tests.ta_52(MainHelpPage_HelpTopics_Tests.java:63)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- ta_52 -->
  <testcase name="ta_52" time="13.669" classname="org.tibco.automation.common.testcases.tsc_navbar.MainHelpPage_HelpTopics_Tests">
    <failure type="java.lang.AssertionError" message="URL Manipulation Found">
      <![CDATA[java.lang.AssertionError: URL Manipulation Foundat org.testng.Assert.fail(Assert.java:96)at org.tibco.automation.common.testcases.tsc_navbar.MainHelpPage_HelpTopics_Tests.ta_52(MainHelpPage_HelpTopics_Tests.java:63)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- ta_52 -->
</testsuite> <!-- org.tibco.automation.common.testcases.tsc_navbar.MainHelpPage_HelpTopics_Tests -->
